// react-version/src/components/WeatherData.tsx
import React from 'react';
import { Cloud, Thermometer, Droplets, Wind, Gauge, TrendingUp, Clock, CloudRain, Info } from 'lucide-react';
import type { WeatherData } from '@mobile-comment-generator/shared';
import { WeatherTimeline } from './WeatherTimeline';

interface WeatherDataProps {
  weather: WeatherData | null;
  metadata?: {
    weather_forecast_time?: string;
    weather_timeline?: {
      summary?: {
        weather_pattern: string;
        temperature_range: string;
        max_precipitation: string;
      };
      past_forecasts?: Array<{
        label: string;
        time: string;
        weather: string;
        temperature: number;
        precipitation: number;
      }>;
      future_forecasts?: Array<{
        label: string;
        time: string;
        weather: string;
        temperature: number;
        precipitation: number;
      }>;
      error?: string;
    };
    selected_weather_comment?: string;
    selected_advice_comment?: string;
  };
  className?: string;
}

const formatDateTime = (dateString: string | undefined) => {
  if (!dateString) return '不明';
  try {
    const date = new Date(dateString.replace('Z', '+00:00'));
    return date.toLocaleString('ja-JP', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit'
    });
  } catch (error) {
    return dateString;
  }
};

export const WeatherDataDisplay: React.FC<WeatherDataProps> = ({
  weather,
  metadata,
  className = '',
}) => {
  if (!weather) {
    return (
      <div className={`text-center py-8 ${className}`}>
        <Cloud className="w-12 h-12 text-gray-300 mx-auto mb-4" />
        <p className="text-gray-500 dark:text-gray-400">天気データを取得中...</p>
      </div>
    );
  }

  const { current, forecast, trend } = weather;

  return (
    <div className={`space-y-6 ${className}`}>
      {/* 予報基準時刻 */}
      {metadata?.weather_forecast_time && (
        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 border border-blue-200 dark:border-blue-700 rounded-lg p-4">
          <div className="flex items-center space-x-2 mb-2">
            <Clock className="w-5 h-5 text-blue-600 dark:text-blue-400" />
            <span className="text-sm font-semibold text-blue-800 dark:text-blue-200">予報基準時刻</span>
          </div>
          <div className="text-blue-700 dark:text-blue-300 font-medium">
            {formatDateTime(metadata.weather_forecast_time)}
          </div>
          <div className="text-xs text-blue-600 dark:text-blue-400 mt-1">
            この時刻を中心とした前後24時間の天気変化を分析してコメントを生成
          </div>
        </div>
      )}

      {/* Weather Timeline - 4時間予報データ */}
      {metadata?.weather_timeline && (
        <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-6 shadow-sm">
          <WeatherTimeline timeline={metadata.weather_timeline} />
        </div>
      )}

      {/* 現在の天気 */}
      <div className="bg-app-surface border border-app-border rounded-lg p-6 shadow-sm">
        <h3 className="text-lg font-medium text-gray-900 mb-4 flex items-center">
          <Cloud className="w-5 h-5 mr-2 text-blue-600" />
          現在の天気
        </h3>
        
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="text-center">
            <div className="flex items-center justify-center mb-2">
              <Thermometer className="w-5 h-5 text-red-500" />
            </div>
            <div className="text-2xl font-bold text-gray-900 dark:text-gray-100">{current.temperature}°C</div>
            <div className="text-sm text-gray-600 dark:text-gray-400">気温</div>
          </div>
          
          <div className="text-center">
            <div className="flex items-center justify-center mb-2">
              <Droplets className="w-5 h-5 text-blue-500" />
            </div>
            <div className="text-2xl font-bold text-gray-900 dark:text-gray-100">{current.humidity}%</div>
            <div className="text-sm text-gray-600 dark:text-gray-400">湿度</div>
          </div>
          
          <div className="text-center">
            <div className="flex items-center justify-center mb-2">
              <Wind className="w-5 h-5 text-green-500" />
            </div>
            <div className="text-2xl font-bold text-gray-900 dark:text-gray-100">{current.windSpeed}m/s</div>
            <div className="text-sm text-gray-600 dark:text-gray-400">風速</div>
          </div>
          
          <div className="text-center">
            <div className="flex items-center justify-center mb-2">
              <Gauge className="w-5 h-5 text-purple-500" />
            </div>
            <div className="text-2xl font-bold text-gray-900 dark:text-gray-100">{current.pressure}hPa</div>
            <div className="text-sm text-gray-600 dark:text-gray-400">気圧</div>
          </div>
        </div>

        <div className="mt-4 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg">
          <div className="flex items-center space-x-2">
            <span className="text-2xl">{current.icon}</span>
            <div>
              <div className="font-medium text-gray-900 dark:text-gray-100">{current.description}</div>
              <div className="text-sm text-gray-600 dark:text-gray-400">風向: {current.windDirection}</div>
            </div>
          </div>
        </div>
      </div>

      {/* 予報データ */}
      {forecast && forecast.length > 0 && (
        <div className="bg-app-surface border border-app-border rounded-lg p-6 shadow-sm">
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-4">基本天気予報</h3>
          
          <div className="space-y-3">
            {forecast.slice(0, 5).map((item, index) => (
              <div key={index} className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-700 rounded-lg">
                <div className="flex items-center space-x-3">
                  <span className="text-xl">{item.icon}</span>
                  <div>
                    <div className="font-medium text-gray-900 dark:text-gray-100">
                      {new Date(item.datetime).toLocaleDateString('ja-JP', {
                        month: 'short',
                        day: 'numeric',
                        hour: '2-digit',
                        minute: '2-digit'
                      })}
                    </div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">{item.description}</div>
                  </div>
                </div>
                
                <div className="text-right">
                  <div className="font-bold text-gray-900 dark:text-gray-100">
                    {item.temperature.max}°C / {item.temperature.min}°C
                  </div>
                  <div className="text-sm text-gray-600 dark:text-gray-400">
                    湿度: {item.humidity}% | 降水: {item.precipitation}mm
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* トレンド情報 */}
      {trend && (
        <div className="bg-app-surface border border-app-border rounded-lg p-6 shadow-sm">
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-4 flex items-center">
            <TrendingUp className="w-5 h-5 mr-2 text-green-600" />
            天気の傾向
          </h3>
          
          <div className="flex items-center space-x-4">
            <div className={`px-3 py-1 rounded-full text-sm font-medium ${
              trend.trend === 'improving' ? 'bg-green-100 text-green-800' :
              trend.trend === 'worsening' ? 'bg-red-100 text-red-800' :
              'bg-gray-100 text-gray-800'
            }`}>
              {trend.trend === 'improving' ? '改善傾向' :
               trend.trend === 'worsening' ? '悪化傾向' : '安定'}
            </div>
            <div className="text-sm text-gray-600 dark:text-gray-400">
              信頼度: {Math.round(trend.confidence * 100)}%
            </div>
          </div>

          <p className="mt-3 text-gray-700 dark:text-gray-300">{trend.description}</p>
        </div>
      )}

      {/* Selected Comments */}
      {(metadata?.selected_weather_comment || metadata?.selected_advice_comment) && (
        <div className="bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20 border border-purple-200 dark:border-purple-700 rounded-lg p-6">
          <div className="flex items-center space-x-2 mb-4">
            <Info className="w-5 h-5 text-purple-600 dark:text-purple-400" />
            <h3 className="text-lg font-semibold text-purple-800 dark:text-purple-200">選択されたコメント</h3>
          </div>
          {metadata.selected_weather_comment && (
            <div className="mb-3">
              <div className="text-sm font-medium text-purple-700 dark:text-purple-300 mb-1">
                <strong>天気コメント:</strong>
              </div>
              <div className="text-purple-800 dark:text-purple-200">
                {metadata.selected_weather_comment}
              </div>
            </div>
          )}
          {metadata.selected_advice_comment && (
            <div>
              <div className="text-sm font-medium text-purple-700 dark:text-purple-300 mb-1">
                <strong>アドバイスコメント:</strong>
              </div>
              <div className="text-purple-800 dark:text-purple-200">
                {metadata.selected_advice_comment}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

// frontend/components/WeatherData.vue
<template>
  <AppCard>
    <template #header>
      <div class="flex items-center justify-between">
        <div class="flex items-center">
          <Icon name="heroicons:cloud-sun" class="w-5 h-5 mr-2" />
          <h2 class="text-lg font-semibold">天気予報データ</h2>
        </div>
        
        <!-- Batch Mode Location Selector -->
        <div v-if="isBatchMode && batchResults && batchResults.length > 1" class="flex items-center space-x-2">
          <span class="text-sm text-gray-600">地点:</span>
          <select 
            :value="selectedIndex"
            @change="emit('update:selectedIndex', Number(($event.target as HTMLSelectElement).value))"
            class="text-sm border border-gray-300 rounded px-2 py-1"
          >
            <option 
              v-for="(result, index) in batchResults" 
              :key="index"
              :value="index"
            >
              {{ result.location }}
            </option>
          </select>
        </div>
      </div>
    </template>

    <div v-if="weatherData && weatherData.metadata" class="space-y-6">
      <!-- Current Weather -->
      <div class="bg-gradient-to-r from-blue-50 to-indigo-50 p-4 rounded-lg">
        <div class="flex items-center justify-between mb-3">
          <h3 class="text-lg font-semibold text-gray-800">現在の天気状況</h3>
          <div class="text-sm text-gray-600">
            {{ formatDateTime(weatherData.metadata.weather_forecast_time) }}
          </div>
        </div>
        
        <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div class="text-center">
            <div class="text-sm text-gray-600">天気</div>
            <div class="text-xl font-bold text-blue-600">{{ weatherData.metadata.weather_condition }}</div>
          </div>
          <div class="text-center">
            <div class="text-sm text-gray-600">気温</div>
            <div class="text-xl font-bold text-red-600">{{ weatherData.metadata.temperature }}°C</div>
          </div>
          <div class="text-center">
            <div class="text-sm text-gray-600">湿度</div>
            <div class="text-xl font-bold text-green-600">{{ weatherData.metadata.humidity }}%</div>
          </div>
          <div class="text-center">
            <div class="text-sm text-gray-600">風速</div>
            <div class="text-xl font-bold text-purple-600">{{ weatherData.metadata.wind_speed }}m/s</div>
          </div>
        </div>
      </div>

      <!-- Weather Timeline -->
      <div v-if="weatherData.metadata.weather_timeline" class="space-y-4">
        <h3 class="text-lg font-semibold text-gray-800">翌日の詳細予報</h3>
        
        <!-- Summary -->
        <div v-if="weatherData.metadata.weather_timeline.summary" class="bg-gray-50 p-4 rounded-lg">
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
            <div>
              <span class="text-gray-600">気温範囲:</span>
              <span class="ml-2 font-medium">{{ weatherData.metadata.weather_timeline.summary.temperature_range }}</span>
            </div>
            <div>
              <span class="text-gray-600">最大降水量:</span>
              <span class="ml-2 font-medium">{{ weatherData.metadata.weather_timeline.summary.max_precipitation }}</span>
            </div>
            <div>
              <span class="text-gray-600">天気パターン:</span>
              <span class="ml-2 font-medium">{{ weatherData.metadata.weather_timeline.summary.weather_pattern }}</span>
            </div>
          </div>
        </div>

        <!-- Future Forecasts -->
        <div v-if="weatherData.metadata.weather_timeline.future_forecasts && weatherData.metadata.weather_timeline.future_forecasts.length > 0">
          <h4 class="text-md font-medium text-gray-700 mb-3">翌日（{{ getDateFromForecast(weatherData.metadata.weather_timeline.future_forecasts[0]) }}）の予報</h4>
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
            <div 
              v-for="forecast in weatherData.metadata.weather_timeline.future_forecasts" 
              :key="forecast.time"
              class="bg-white border border-gray-200 rounded-lg p-3 shadow-sm"
            >
              <div class="text-center">
                <div class="text-sm font-medium text-gray-800">{{ forecast.label }}</div>
                <div class="text-lg font-bold text-blue-600 my-1">{{ forecast.weather }}</div>
                <div class="text-md font-semibold text-red-600">{{ forecast.temperature }}°C</div>
                <div v-if="forecast.precipitation > 0" class="text-sm text-blue-500 mt-1">
                  降水量: {{ forecast.precipitation }}mm
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Past Forecasts (if available) -->
        <div v-if="weatherData.metadata.weather_timeline.past_forecasts && weatherData.metadata.weather_timeline.past_forecasts.length > 0">
          <h4 class="text-md font-medium text-gray-700 mb-3">過去の実況</h4>
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
            <div 
              v-for="past in weatherData.metadata.weather_timeline.past_forecasts" 
              :key="past.time"
              class="bg-gray-50 border border-gray-200 rounded-lg p-3"
            >
              <div class="text-center">
                <div class="text-sm font-medium text-gray-600">{{ past.label }}</div>
                <div class="text-lg font-bold text-gray-700 my-1">{{ past.weather }}</div>
                <div class="text-md font-semibold text-gray-600">{{ past.temperature }}°C</div>
                <div v-if="past.precipitation > 0" class="text-sm text-gray-500 mt-1">
                  降水量: {{ past.precipitation }}mm
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- No Data State -->
    <div v-else class="text-center py-12">
      <Icon name="heroicons:cloud" class="w-16 h-16 text-gray-300 mx-auto mb-4" />
      <div class="text-lg font-medium text-gray-900">天気データなし</div>
      <div class="text-sm text-gray-500 mt-2">
        コメントを生成すると、詳細な天気予報データが表示されます
      </div>
    </div>
  </AppCard>
</template>

<script setup lang="ts">
import { defineProps } from 'vue'

interface Props {
  weatherData?: any
  isBatchMode?: boolean
  batchResults?: any[]
  selectedIndex?: number
}

const props = defineProps<Props>()
const emit = defineEmits<{
  'update:selectedIndex': [value: number]
}>()

const formatDateTime = (dateString: string) => {
  if (!dateString) return '不明'
  try {
    const date = new Date(dateString)
    return date.toLocaleString('ja-JP', {
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit'
    })
  } catch (error) {
    return dateString
  }
}

const getDateFromForecast = (forecast: any) => {
  if (!forecast || !forecast.time) return ''
  try {
    // "06/24 09:00" format
    const [date] = forecast.time.split(' ')
    return date
  } catch (error) {
    return ''
  }
}
</script>

<style scoped>
.weather-data {
  background: white;
  border-radius: 16px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  overflow: hidden;
}

.component-header {
  background: linear-gradient(135deg, #0C419A 0%, #6BA2FC 100%);
  color: white;
  padding: 1.5rem 2rem;
  border-bottom: 3px solid #6BA2FC;
}

.component-header h3 {
  font-size: 1.4rem;
  font-weight: 700;
  margin: 0;
  text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.2);
}

.weather-content {
  padding: 2rem;
}
</style>
